In [ ]:
#Araceli Olarte Ledezma
#A01686220

In [5]:
import numpy as np
a=[1,2,3,4,5]


In [9]:
x = np.array(a)

In [10]:
print (x)

[1 2 3 4 5]


In [7]:

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 1
a[1]: 2
a[2]: 3
a[3]: 4
a[4]: 5


In [8]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [11]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [12]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

In [13]:
print (A)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
np.dot(A,B)

<class 'ValueError'>: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [16]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [17]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [18]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])